version: '3'

networks:
  portaria:

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: admin
      MYSQL_PASSWORD: "admin"
      MYSQL_DATABASE: portaria
    networks: 
      - portaria
    ports:
      - "3309:3306"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/src
    ports:
      - "8040:8000"
    depends_on: 
      - db
    networks:
      - portaria