# Generated by Django 2.1.2 on 2018-11-01 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 13, 43, 39, 268046), verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto_adicional',
            field=models.ImageField(blank=True, upload_to='cadastro/static/img/upload/visitantes/adicional/2018/11/01', verbose_name='Foto Adicional'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto_principal',
            field=models.ImageField(blank=True, default='cadastro/static/img/user.svg', upload_to='cadastro/static/img/upload/visitantes/principal/2018/11/01', verbose_name='Foto do Visitante'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='data',
            field=models.DateField(default=datetime.datetime(2018, 11, 1, 13, 43, 39, 269047), verbose_name='Data'),
        ),
    ]
