# Generated by Django 2.1.2 on 2018-10-16 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime(2018, 10, 16, 17, 59, 33, 626490), verbose_name='Data')),
                ('horarioEntrada', models.TimeField(verbose_name='Horário de Entrada')),
                ('horarioSaida', models.TimeField(blank=True, null=True, verbose_name='Horário de Saída')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor da Visita')),
                ('observacao', models.TextField(blank=True, max_length=1000, verbose_name='Observação')),
                ('pessoa', models.ForeignKey(on_delete=models.CASCADE, to='cadastro.Pessoa')),
            ],
        ),
    ]
