# Generated by Django 2.1.2 on 2018-10-10 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 10, 19, 36, 48, 309982, tzinfo=utc), verbose_name='Data de Cadastro'),
        ),
    ]
